context("utils")

test_that("argument checking works for integer", {
  expect_true(is_int(1L))
  expect_false(is_int(integer()))
  expect_true(is_int(integer(), n_elem = eq(0L)))
  expect_false(is_int(c(1L, NA)))
  expect_false(is_int(NA, allow_na = TRUE))
  expect_true(is_int(NA_integer_, allow_na = TRUE))
  expect_true(is_int(c(1L, NA), allow_na = TRUE))
  expect_false(is_int(NULL))
  expect_true(is_int(NULL, allow_null = TRUE))
  expect_false(is_int(list(NULL), allow_null = TRUE))
  expect_false(is_int(list(1L)))
  expect_false(is_int(1L, n_elem = eq(2L)))
  expect_true(is_int(c(1L, 2L), n_elem = eq(2L)))
  expect_false(is_int(c(1L, 2L), n_elem = gt(2L)))
})

test_that("argument checking works for logical", {
  expect_true(is_lgl(TRUE))
  expect_false(is_lgl(integer()))
  expect_false(is_lgl(logical()))
  expect_true(is_lgl(logical(), n_elem = eq(0L)))
  expect_false(is_lgl(c(TRUE, NA)))
  expect_true(is_lgl(NA, allow_na = TRUE))
  expect_true(is_lgl(c(TRUE, NA), allow_na = TRUE))
  expect_false(is_lgl(NULL))
  expect_true(is_lgl(NULL, allow_null = TRUE))
  expect_false(is_lgl(list(NULL), allow_null = TRUE))
  expect_false(is_lgl(list(TRUE)))
  expect_false(is_lgl(TRUE, n_elem = eq(2L)))
  expect_true(is_lgl(c(TRUE, TRUE), n_elem = eq(2L)))
  expect_false(is_lgl(c(TRUE, TRUE), n_elem = gt(2L)))
})

test_that("argument checking works for character", {
  expect_true(is_chr("a"))
  expect_false(is_chr(""))
  expect_false(is_chr(c("a", NA)))
  expect_false(is_chr(NA, allow_na = TRUE))
  expect_true(is_chr(NA_character_, allow_na = TRUE))
  expect_true(is_chr(c("a", NA), allow_na = TRUE))
  expect_false(is_chr(NULL))
  expect_true(is_chr(NULL, allow_null = TRUE))
  expect_false(is_chr(list(NULL), allow_null = TRUE))
  expect_false(is_chr(list("a")))
  expect_true(is_chr("ab"))
  expect_true(is_chr("ab", n_char = gte(2L)))
  expect_false(is_chr("a", n_char = gte(2L)))
  expect_false(is_chr("a", n_char = gt(1L)))
  expect_false(is_chr("ab", n_char = lt(1L)))
  expect_true(is_chr("ab", n_char = lte(2L)))
  expect_false(is_chr("a", n_elem = eq(2L)))
  expect_true(is_chr(c("a", "b"), n_elem = eq(2L)))
  expect_false(is_chr(c("a", "b"), n_elem = gt(2L)))
})
