
#' @title Generate SQL for a table definition
#'
#' @description Generate SQL, that can be used for table definitions in
#' CREATE TABLE statements.
#'
#' @name tbl_spec
#'
#' @param ... Arguments passed to the S3 methods
#'
#' @return SQL to be used in a CREATE table statement
#'
#' @param name String specifying the table name
#' @param cols,keys Column and key specifications as generated by
#' \code{col_spec} and the various key spec functions. If multiple
#' columns/keys are passed, wrap function calls in \code{list}.
#' @param temp Logical switch specifying whether the table is temporary
#' (visible only within the current session, and dropped automatically when
#' the session is closed)
#' @param force Logical, if FALSE, an error is thrown if the table exists, if
#' TRUE, nothing happens if the table already exists.
#' @param engine The storage engine (defaults to InnoDB)
#' @param auto_incr The initial \code{AUTO_INCREMENT} value for the table.
#' @param char_set Specifies a default character set for the table.
#' @param collate Specifies a default collation for the table.
#' @param comment A comment for the table, up to 2048 characters long.
#' @param table_options Further table options such as \code{COMPRESSION},
#' \code{ENCRYPTION}, \code{ROW_FORMAT}, etc. Must be one or more SQL strings
#' and multiple will end up separated by single spaces.
#' @param partition Table partition settings. Currently only NULL is accepted.
#'
#' @section TODO: create single \code{key_spec} function like \code{col_spec}
#' @section TODO: implement table partitioning
#'
#' @export
#'
tbl_spec <- function(name = paste(sample(letters, 10, TRUE),
                       collapse = ""
                     ),
                     cols = col_id(),
                     keys = NULL,
                     temp = FALSE,
                     force = FALSE,
                     engine = "InnoDB",
                     auto_incr = NA_integer_,
                     char_set = NA_character_,
                     collate = NA_character_,
                     comment = NA_character_,
                     table_options = NULL,
                     partition = NULL,
                     ...) {

  stopifnot(
    is_chr(name, n_elem = eq(1L)),
    is_lgl(temp, n_elem = eq(1L)),
    is_lgl(force, n_elem = eq(1L)),
    is_int(auto_incr,
      n_elem = eq(1L), allow_na = TRUE,
      strict = FALSE
    ),
    is_chr(char_set, n_elem = eq(1L), allow_na = TRUE),
    is_chr(collate, n_elem = eq(1L), allow_na = TRUE),
    is_chr(comment, n_elem = eq(1L), allow_na = TRUE),
    is_chr(engine, n_elem = eq(1L))
  )

  obj <- as.list(environment())
  new_sqlr(obj, subclass = "tbl_spec")
}

#' @export sqlr_render.sqlr_tbl_spec
#' @method sqlr_render sqlr_tbl_spec
#' @export
sqlr_render.sqlr_tbl_spec <- function(x, con, ...) UseMethod("sqlr_render.sqlr_tbl_spec", con)

#' @method sqlr_render.sqlr_tbl_spec MariaDBConnection
#' @export
sqlr_render.sqlr_tbl_spec.MariaDBConnection <- function(x, con, ...) {
  list2env(x, environment())

  if (!is.null(table_options)) {
    stopifnot(inherits(table_options, "SQL"), length(table_options) >= 1)
  }
  if (!is.null(partition)) stop("not implemented yet.")

  if (!is.list(cols)) cols <- list(cols)
  # FIXME
  # stopifnot(all(sapply(cols, inherits, "sqlr_col"), length(cols) >= 1))

  if (!is.null(keys)) {
    if (!is.list(keys)) keys <- list(keys)
    # stopifnot(all(sapply(keys, inherits, "SQL")), length(keys) >= 1)
  }

  DBI::SQL(paste0(
    "CREATE",
    if (temp) {
      " TEMPORARY"
    },
    " TABLE",
    if (force) {
      " IF NOT EXISTS"
    },
    " ", DBI::dbQuoteIdentifier(con, name),
    " (",
    paste(sqlr_render(cols, con), collapse = ", "),
    if (!is.null(keys)) {
      paste(",", paste(sqlr_render(keys, con), collapse = ", "))
    },
    ")",
    " ENGINE = ", DBI::dbQuoteString(con, engine),
    if (!is.na(auto_incr)) {
      paste(" AUTO_INCREMENT =", auto_incr)
    },
    if (!is.na(char_set)) {
      paste(" DEFAULT CHARACTER SET =", char_set)
    },
    if (!is.na(collate)) {
      paste(" DEFAULT COLLATE =", collate)
    },
    if (!is.na(comment)) {
      paste(" COMMENT =", comment)
    },
    if (!is.null(table_options)) {
      paste0(" ", paste(table_options, collapse = " "))
    }
  ))
}
